//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstMVCProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class username
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public username()
        {
            this.chats = new HashSet<chat>();
            this.chats1 = new HashSet<chat>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public string password_ { get; set; }
        public string mail { get; set; }
        public Nullable<int> isActive { get; set; }
        public Nullable<int> isOnline { get; set; }
        public byte[] image { get; set; }
        public Nullable<System.DateTime> LastSeen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chat> chats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chat> chats1 { get; set; }
    }
}
